export enum MicroserviceType {
  DELIVERY,
  DEPLOY,
  DISCOVERY,
  OFFERING,
  PROJECT_MANAGEMENT,
  UPLOAD,
  GET_MAP,
  DEVICE,
  SBOM_GENERATOR,
}

export const MicroserviceName = {
  DELIVERY_SERVICE: "DELIVERY_SERVICE",
  DEPLOY_SERVICE: "DEPLOY_SERVICE",
  DISCOVERY_SERVICE: "DISCOVERY_SERVICE",
  OFFERING_SERVICE: "OFFERING_SERVICE",
  PROJECT_MANAGEMENT_SERVICE: "PROJECT_MANAGEMENT_SERVICE",
  UPLOAD_SERVICE: "UPLOAD_SERVICE",
  GET_MAP_SERVICE: "GET_MAP_SERVICE",
  DEVICE_SERVICE: "DEVICE_SERVICE",
  SBOM_GENERATOR_SERVICE: "SBOM_GENERATOR_SERVICE",
}

export interface MicroserviceModuleOptions {
  name: string,
  type: MicroserviceType
  id?: string
}